name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target:
        description: "Select what to run"
        required: false
        default: "all"
        type: choice
        options:
          - lint
          - ui
          - api
          - all
env:
  API_URL: ${{ vars.API_URL }}
  API_USER_NAME: ${{ vars.API_USER_NAME }}
  API_USER_PASSWORD: ${{ secrets.API_USER_PASSWORD }}
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
  UI_BASE_URL: ${{ vars.UI_BASE_URL }}
  CARTO_BASE_URL: ${{ vars.CARTO_BASE_URL }}
  UI_USERNAME: ${{ vars.UI_USERNAME }}
  UI_PASSWORD: ${{ secrets.UI_PASSWORD }}

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run lint

  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target == 'api' || github.event.inputs.target == 'all' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - name: Run API tests
        run: npm run test:api

      - name: Upload API HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-report
          path: playwright-report/
          retention-days: 15

  ui-tests:
    name: Run UI Tests (Chromium + Firefox)
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target == 'ui' || github.event.inputs.target == 'all' }}
    strategy:
      matrix:
        browser: [ui-chromium, ui-firefox]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run UI tests
        run: npm run test:ui:all
      - name: Upload UI HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.browser }}-report
          path: playwright-report/
          retention-days: 15

  all-tests:
    name: Run All Tests (UI + API)
    runs-on: ubuntu-latest
    needs: [ui-tests, api-tests]
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target == 'all' }}
    steps:
      - run: echo "All UI and API Tests executed successfully."
